ClarkCodingChallenge/Entities/Contact.cs
using System.ComponentModel.DataAnnotations;

namespace ClarkCodingChallenge.Entities
{
    public class Contact
    {
        [Key]
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        public string LastName { get; set; }

        [Required]
        public string FirstName { get; set; }
    }
}

ClarkCodingChallenge/Models/ErrorViewModel.cs
namespace ClarkCodingChallenge.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ClarkCodingChallenge/Controllers/ContactsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ClarkCodingChallenge.Models;
using ClarkCodingChallenge.Entities;
using System.Collections.Generic;
using ClarkCodingChallenge.DataAccess;
using System;
using System.Net;

namespace ClarkCodingChallenge.Controllers
{
    public class ContactsController : Controller
    {
        private readonly IContactsRepository _contactsService;

        public ContactsController(IContactsRepository contactsService)
        {
            _contactsService = contactsService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult<Contact> GetContactByEmail(string email)
        {
            var contact = _contactsService.GetContactByEmail(email);

            if (contact == null)
            {
                return NotFound();
            }

            return Ok(contact);
        }

        public IActionResult AddContact()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddContact(Contact contact)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _contactsService.AddContact(contact);
                }
                catch (Exception)
                {
                    return StatusCode(500);
                }

                return CreatedAtAction(
                    "GetContactByEmail",
                    new { email = contact.Email },
                    contact);
            }
            else
            {
                return BadRequest();
            }
        }

        [HttpGet]
        public ActionResult<IEnumerable<Contact>> GetMailingListEntries(
            string lastName, 
            string sortOrder = "asc")
        {
            var contacts = _contactsService.GetMailingListEntries(lastName, sortOrder);
        
            return Ok(contacts);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ClarkCodingChallenge/Views/Contacts/AddContact.cshtml
@page
@addTagHelper*, Microsoft.AspNetCore.Mvc.TagHelpers
@model ClarkCodingChallenge.Entities.Contact
@{
    ViewData["Title"] = "Add Contact";
}

<div class="row text-center">
    <form asp-controller="Contacts" asp-action="AddContact" method="post">
        <div>
            <label for="lastName">Last Name</label>
            <input asp-for="LastName" type="text" id="lastName" name="LastName" required />
            <span asp-validation-for="LastName"></span>
        </div>

        <div>
            <label for="firstName">First Name</label>
            <input asp-for="FirstName" type="text" id="firstName" name="FirstName" required />
            <span asp-validation-for="FirstName"></span>
        </div>

        <div>
            <label for="email">Email</label>
            <input asp-for="Email" type="email" id="email" name="Email"/>
            <span asp-validation-for="Email"></span>
        </div>

        <div>
            <input type="submit" value="Submit" />
        </div>
    </form>
</div>

ClarkCodingChallenge/Views/Contacts/Index.cshtml
@{
    ViewData["Title"] = "Contacts Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

ClarkCodingChallenge/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClarkCodingChallenge</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Clark Coding Challenge</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacts" asp-action="Index">Contacts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacts" asp-action="AddContact">Add Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Clark Coding Challenge
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>